// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: mail.proto

package mail

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	MailService_SendActivatonMessage_FullMethodName          = "/mail.MailService/SendActivatonMessage"
	MailService_SendAdminRoleIsSettedMessage_FullMethodName  = "/mail.MailService/SendAdminRoleIsSettedMessage"
	MailService_SendMemberRoleIsSettedMessage_FullMethodName = "/mail.MailService/SendMemberRoleIsSettedMessage"
)

// MailServiceClient is the client API for MailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailServiceClient interface {
	SendActivatonMessage(ctx context.Context, in *ActivationMessageData, opts ...grpc.CallOption) (*Empty, error)
	SendAdminRoleIsSettedMessage(ctx context.Context, in *RoleIsSetedMessageData, opts ...grpc.CallOption) (*Empty, error)
	SendMemberRoleIsSettedMessage(ctx context.Context, in *RoleIsSetedMessageData, opts ...grpc.CallOption) (*Empty, error)
}

type mailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailServiceClient(cc grpc.ClientConnInterface) MailServiceClient {
	return &mailServiceClient{cc}
}

func (c *mailServiceClient) SendActivatonMessage(ctx context.Context, in *ActivationMessageData, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MailService_SendActivatonMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendAdminRoleIsSettedMessage(ctx context.Context, in *RoleIsSetedMessageData, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MailService_SendAdminRoleIsSettedMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendMemberRoleIsSettedMessage(ctx context.Context, in *RoleIsSetedMessageData, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MailService_SendMemberRoleIsSettedMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServiceServer is the server API for MailService service.
// All implementations must embed UnimplementedMailServiceServer
// for forward compatibility
type MailServiceServer interface {
	SendActivatonMessage(context.Context, *ActivationMessageData) (*Empty, error)
	SendAdminRoleIsSettedMessage(context.Context, *RoleIsSetedMessageData) (*Empty, error)
	SendMemberRoleIsSettedMessage(context.Context, *RoleIsSetedMessageData) (*Empty, error)
	mustEmbedUnimplementedMailServiceServer()
}

// UnimplementedMailServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMailServiceServer struct {
}

func (UnimplementedMailServiceServer) SendActivatonMessage(context.Context, *ActivationMessageData) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendActivatonMessage not implemented")
}
func (UnimplementedMailServiceServer) SendAdminRoleIsSettedMessage(context.Context, *RoleIsSetedMessageData) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAdminRoleIsSettedMessage not implemented")
}
func (UnimplementedMailServiceServer) SendMemberRoleIsSettedMessage(context.Context, *RoleIsSetedMessageData) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMemberRoleIsSettedMessage not implemented")
}
func (UnimplementedMailServiceServer) mustEmbedUnimplementedMailServiceServer() {}

// UnsafeMailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailServiceServer will
// result in compilation errors.
type UnsafeMailServiceServer interface {
	mustEmbedUnimplementedMailServiceServer()
}

func RegisterMailServiceServer(s grpc.ServiceRegistrar, srv MailServiceServer) {
	s.RegisterService(&MailService_ServiceDesc, srv)
}

func _MailService_SendActivatonMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivationMessageData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendActivatonMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailService_SendActivatonMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendActivatonMessage(ctx, req.(*ActivationMessageData))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendAdminRoleIsSettedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleIsSetedMessageData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendAdminRoleIsSettedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailService_SendAdminRoleIsSettedMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendAdminRoleIsSettedMessage(ctx, req.(*RoleIsSetedMessageData))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendMemberRoleIsSettedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleIsSetedMessageData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendMemberRoleIsSettedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailService_SendMemberRoleIsSettedMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendMemberRoleIsSettedMessage(ctx, req.(*RoleIsSetedMessageData))
	}
	return interceptor(ctx, in, info, handler)
}

// MailService_ServiceDesc is the grpc.ServiceDesc for MailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mail.MailService",
	HandlerType: (*MailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendActivatonMessage",
			Handler:    _MailService_SendActivatonMessage_Handler,
		},
		{
			MethodName: "SendAdminRoleIsSettedMessage",
			Handler:    _MailService_SendAdminRoleIsSettedMessage_Handler,
		},
		{
			MethodName: "SendMemberRoleIsSettedMessage",
			Handler:    _MailService_SendMemberRoleIsSettedMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail.proto",
}
