server:
    url: ":80"

logger:
    level: "info"
    add_source: false
    is_json: true
    set_default: true

postgres:
    host: "localhost"
    port: "5432"
    username: "admin"
    dbname: "postgres"
    sslmode: "disable"

redis:
    host: "localhost"
    port: "6379"
    db: "1"